apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: aap
spec:
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    file_storage_access_mode: ReadWriteOnce
    file_storage_size: 10Gi
    content:
      replicas: 1
    worker:
      replicas: 1
